race_monitor:
  ros__parameters:
    # ========================================
    # RACE MONITORING PARAMETERS
    # ========================================

    # Start/finish line configuration
    start_line_p1: [0.0, -1.0] # Bottom point of start line [x, y]
    start_line_p2: [0.0, 1.0] # Top point of start line [x, y]
    required_laps: 5 # Number of laps to complete race
    debounce_time: 2.0 # Debounce time for lap detection (seconds)
    output_file: "race_results.csv" # CSV file for race results
    frame_id: "map" # Frame ID for visualization

    # ========================================
    # RESEARCH & ANALYSIS PARAMETERS
    # ========================================

    # Controller identification for research comparison
    controller_name: "custom_controller" # Name of the controller being tested
    experiment_id: "exp_001" # Experiment identifier for this run
    test_description: "Custom controller vs MPC/LQR comparison"

    # Advanced metrics for research analysis
    enable_advanced_metrics: true # Enable comprehensive metric calculations
    calculate_all_statistics: true # Calculate mean, median, std, min, max (not just RMSE)
    analyze_rotation_errors: true # Include orientation analysis
    enable_geometric_analysis: true # Arc length, curvature analysis
    enable_filtering_analysis: true # Apply and analyze trajectory filtering

    # Research-specific evaluation modes
    detailed_lap_analysis: true # Detailed per-lap breakdown
    comparative_analysis: true # Enable comparison with reference controllers
    statistical_significance: true # Calculate statistical significance tests

    # ========================================
    # EVO INTEGRATION PARAMETERS
    # ========================================

    # Enable/disable trajectory evaluation
    enable_trajectory_evaluation: true

    # Evaluation timing options (choose one):
    # Option 1: Time-based evaluation (evaluate every X seconds)
    evaluation_interval_seconds: 0

    # Option 2: Lap-based evaluation (evaluate every X laps)
    evaluation_interval_laps: 1 # 0 = disable lap-based evaluation

    # Option 3: Distance-based evaluation (evaluate every X meters)
    evaluation_interval_meters: 0.0 # 0 = disable distance-based evaluation

    # ========================================
    # REFERENCE TRAJECTORY CONFIGURATION
    # ========================================

    # File-based reference trajectory
    reference_trajectory_file: "horizon_mapper/horizon_mapper/ref_trajectory.csv"
    reference_trajectory_format: "csv" # csv, tum, kitti

    # Horizon mapper interface (real-time reference trajectory)
    enable_horizon_mapper_reference: true
    horizon_mapper_reference_topic: "/horizon_mapper/reference_trajectory"

    # Use complete reference path instead of reference trajectory points
    use_complete_reference_path: true
    horizon_mapper_path_topic: "/horizon_mapper/reference_path"

    # ========================================
    # ADVANCED FILE OUTPUT FOR RESEARCH
    # ========================================

    # Enhanced data export
    export_to_pandas: true # Export data to pandas DataFrame
    save_detailed_statistics: true # Save comprehensive statistics
    save_filtered_trajectories: true # Save both raw and filtered trajectories
    export_research_summary: true # Generate research-ready summary

    # Research file formats
    output_formats: ["csv", "json", "pickle", "mat"] # Multiple formats for analysis tools
    include_timestamps: true # Include detailed timestamp information
    save_intermediate_results: true # Save results after each lap

    # ========================================
    # TRAJECTORY ANALYSIS SETTINGS
    # ========================================

    # Data storage
    save_trajectories: true
    trajectory_output_directory: "trajectory_evaluation"

    # Metrics to calculate
    evaluate_smoothness: true # Calculate trajectory smoothness
    evaluate_consistency: true # Calculate trajectory consistency
    evaluate_efficiency: true # Calculate path efficiency metrics
    evaluate_aggressiveness: true # Calculate driving aggressiveness
    evaluate_stability: true # Calculate control stability metrics

    # Advanced EVO metrics
    pose_relations: ["translation_part", "rotation_part", "full_transformation"]
    statistics_types: ["rmse", "mean", "median", "std", "min", "max", "sse"]

    # Filtering options for noise reduction
    apply_trajectory_filtering: true
    filter_types: ["motion", "distance", "angle"]
    filter_parameters:
      motion_threshold: 0.1 # Minimum motion for filtering
      distance_threshold: 0.05 # Distance threshold for filtering
      angle_threshold: 0.1 # Angle threshold for filtering

    # ========================================
    # GRAPH GENERATION SETTINGS
    # ========================================

    # Enable/disable automatic graph generation
    auto_generate_graphs: true
    graph_output_directory: "trajectory_evaluation/graphs"
    graph_formats: ["png", "pdf"] # png, pdf, svg, html

    # Plot appearance settings
    plot_figsize: [12.0, 8.0] # Figure size [width, height]
    plot_dpi: 300 # DPI for saved images
    plot_style: "seaborn" # matplotlib style
    plot_color_scheme: "viridis" # Color scheme for multiple trajectories

    # Types of graphs to generate
    generate_trajectory_plots: true     # 2D/3D trajectory visualization
    generate_xyz_plots: true           # X, Y, Z position over time
    generate_rpy_plots: true           # Roll, Pitch, Yaw over time
    generate_speed_plots: true         # Velocity analysis
    generate_error_plots: true         # APE/RPE error analysis
    generate_metrics_plots: true       # Smoothness/consistency over time

    # ========================================
    # F1TENTH INTERFACE SETTINGS
    # ========================================

    # Enable/disable F1Tenth vehicle state interface
    enable_f1tenth_interface: true
    f1tenth_vehicle_state_topic: "/vehicle_state"
    f1tenth_constrained_state_topic: "/constrained_vehicle_state"

    
  # ========================================
  # F1TENTH INTERFACE SETTINGS
  # ========================================
  
  # Enable/disable F1Tenth vehicle state interface
  enable_f1tenth_interface: true
  f1tenth_vehicle_state_topic: '/vehicle_state'
  f1tenth_constrained_state_topic: '/constrained_vehicle_state'



  # ========================================
  # COMPUTATIONAL PERFORMANCE MONITORING
  # ========================================
  
  # Enable/disable computational performance monitoring
  enable_computational_monitoring: true
  
  # Odometry input topics
  odometry_topics:
    - name: "car_state/odom"
      message_type: "nav_msgs/Odometry"
      enabled: true
    - name: "/ekf/odometry"
      message_type: "nav_msgs/Odometry" 
      enabled: false
    - name: "/fusion/odom"
      message_type: "nav_msgs/Odometry"
      enabled: false
    - name: "/localization/pose"
      message_type: "geometry_msgs/PoseWithCovarianceStamped"
      enabled: false
  
  # Control command output topics 
  control_command_topics:
    - name: "/drive"
      message_type: "ackermann_msgs/AckermannDriveStamped"
      enabled: true
    - name: "/cmd_vel"
      message_type: "geometry_msgs/Twist"
      enabled: false
    - name: "/ackermann_cmd"
      message_type: "ackermann_msgs/AckermannDriveStamped"
      enabled: false
    - name: "/controller/cmd"
      message_type: "ackermann_msgs/AckermannDriveStamped"
      enabled: false
    - name: "/mpc_controller/cmd"
      message_type: "ackermann_msgs/AckermannDriveStamped"
      enabled: false
  
  # Performance monitoring configuration
  monitoring_window_size: 100                       # Number of samples to keep in memory
  cpu_monitoring_interval: 0.1                      # CPU monitoring interval (seconds)
  
  # Performance logging
  enable_performance_logging: true                  # Enable periodic performance logging
  performance_log_interval: 5.0                     # Performance logging interval (seconds)
  
  # Performance thresholds for analysis
  max_acceptable_latency_ms: 50.0                   # Maximum acceptable control loop latency (ms)
  target_control_frequency_hz: 50.0                 # Target control frequency (Hz)
  max_acceptable_cpu_usage: 80.0                    # Maximum acceptable CPU usage (%)
  max_acceptable_memory_mb: 512.0                   # Maximum acceptable memory usage (MB)
